on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI tests
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.12.3'

      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
